### PR TITLE
Updated for aws api changes.

### PR DESCRIPTION
**Pull request by nadnerb**
Hey mate, this compiles, however I am getting a `ERROR: NotFoundException: Invalid keyId` exception when trying to encrypt. Everything looks ok, never used KMS before though.

### CODE REVIEW

**Comment by mdub** [comment]
Dumb question: does the key you're specifying exist?

Keys are region-specific, so you might need to use `--region` to target the right one.

If that doesn't work, please provide more detail: how are you invoking it?

**Comment by nadnerb** [comment]
Yep, it exists, I am on a box that has the role that can use it as well. I
will look at the cli tomorrow to see where I am going wrong.

**Comment by nadnerb** [comment]
Ok, I thought I would have a quick look before I went to bed and now feel a bit silly, I was using the alias name, not the id. It all works now.. however you still won't be able to compile against later version of the aws-sdk-go unless you update to use `github.com/aws/aws-sdk-go/aws/session`.

**Comment by mdub** [comment]
Righto.  I'm pretty sure aliases work, if you prefix them with "alias/".

**Comment by mdub** [comment]
Oh wait, this is a PR - sorry.

**Pull request merged**
